### ISSUE TITLE
daemon stops working when uncaught exception is thrown in daemon code

### ISSUE THREAD

**Issue by nfcampos** [CrowdProcess/tqueue#1]
eg.
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nuno/cp/tqueue/tqueue/daemon.py", line 118, in <module>
    daemon()
  File "/Users/nuno/cp/tqueue/tqueue/daemon.py", line 88, in daemon
    kill_session_if_needed()
  File "/Users/nuno/cp/tqueue/tqueue/daemon.py", line 69, in kill_session_if_needed
    PROCESSES[sessid].terminate()
KeyError: '573595bc9e61fe0d57e16a6c-5735fc8d009f54be77871ebf'
```

**Comment by hershaw** [comment]
I'm not sure what this particular bug was due to but I think it was due problems with handling session init failure. I have made this more robust so that session which have failed to initialize are handled gracefully and will try to be initted again the next time a task for that session comes in.

Should keep an eye out for this though, not 100% sure I've fixed this particular bug.
